### ISSUE TITLE
Ruby Conf China 2013 售票需求

### ISSUE THREAD

**Issue by saberma** [19wu/19wu#449]
前几天跟 @lgn21st 确定，Ruby Conf China 2013 大会将使用 19屋 作为售票平台，根据本次大会的需要，将功能按角色整理如下：
#### 活动管理员
- [x] 创建票种：个人票、公司票（是否提供发票） #450 
- [x] 设置总票数，而不对票种单独设置票数 #450 
- [x] 申请退款 #573 
- [ ] 查看销售情况：已售票数、余票（包括未支付的票数）、实际余票、订单数、成功订单数（已支付）、收入、支出（发票税金和快递费用 、支付宝手续费及退款费用）、退款订单数
- [x] 查看订单列表和订单详情 #557
- [x] 导出 CSV ，用于打印签到表，无法通过在线签到时可以临时使用签到表（订单号、email、姓名、门票数量、是否公司票、金额、订单日期）#596
#### 用户
- [x] 在活动页面选择票种和票数报名（总票数-1）#451
- [x] 下单成功、支付成功后系统，系统会向用户和活动管理员发送邮件通知 #464 
- [x] 公司票的用户需要录入发票抬头、收货地址、收货人、手机号码 #463 
- [x] 通过支付宝进行支付操作（即时到帐） #451
- [x] 支付出现问题时可以通过【我的订单】记录、或者下单时的确认邮件重新支付 #469
- [x] 支付成功后，系统向用户手机发送签到码 #470
- [x] 在【我的订单】中取消订单 #471
- [x] 在【我的订单】中申请退款 #472

注意要限制用户重复点击提交按钮，避免出现多次下单的情况
#### 签到管理员
- [x] 在现场根据用户的签到码，为用户换取胸牌（要考虑已退款签到码） #536 
#### 19屋管理员
- [x] 查看需要提供发票的公司票订单 #597 
- [x] 录入快递单号，系统向用户发送邮件，提醒发票货件已经发货 #597 
- [x] 可以对汇款的订单进行确认支付 #570
- [x] 处理退款申请 #574 #473
#### 系统
- [x] 超过 3 天未支付的订单自动取消（总票数加1）
- [x] 总票数为零，则限制报名 #465
#### 待讨论需求
- [x] 是否需要设置价格规则：在某个截止时间点前报名前的价格为优惠价，之后为原价？
- [x] 是否需要支持匿名用户报名？
- [x] 现在的用户姓名是非必填的，在报名的时候是否需要用户录入（签到表是否会用到）？
- [x] 虽然活动有两天，只要用户在第一天换取胸牌后，第二天就不需要再签到了，是这样的吧？
- [x] 是否需要提供【签到管理员】的协作角色，只可以进行签到操作，避免误操作修改活动信息？
#### 检查上一年出现的问题
- [x] 部分用户支付成功后未能更新订单状态（这部分用户在支付成功后直接关掉浏览器，支付宝服务器发送的同步请求未能成功）
- [x] 升级Gem后导致用户无法支付，支付签名不正确

稍后会转成一个个独立的 Issue 任务。

cc @lgn21st @doitian @windy @jasl @sishen
